[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "0xfafafa"
foreground = "0x333333"

[colors.normal]
black = "0x333333"
red = "0xd32f2f"
green = "0x558b2f"
yellow = "0xf9a825"
blue = "0x1565c0"
magenta = "0x7b1fa2"
cyan = "0x00838f"
white = "0xf5f5f5"

[colors.bright]
black = "0x666666"
red = "0xe53935"
green = "0x7cb342"
yellow = "0xffb300"
blue = "0x1e88e5"
magenta = "0x9c27b0"
cyan = "0x00acc1"
white = "0xffffff"

[window]
decorations_theme_variant = "Light"
